[toolchain]
channel = "1.93.1"

# Default profile includes `rustfmt`, `clippy`, `rust-docs`.
# https://rust-lang.github.io/rustup/concepts/profiles.html
profile = "default"
components = ["rust-analyzer", "rust-src"]

