//
//Exposes protobuf types generated by prost. 
//Clippy errors are redundant to fix for these.
#![allow(dead_code)]
#![allow(clippy::all)]

pub(crate) mod opentelemetry {
    pub(crate) mod proto {
        pub(crate) mod collector {
            pub(crate) mod metrics {
                pub(crate) mod v1 {
                    include!(concat!(
                        env!("OUT_DIR"),
                        "/opentelemetry.proto.collector.metrics.v1.rs"
                    ));
                }
            }
        }

        pub(crate) mod common {
            pub(crate) mod v1 {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.common.v1.rs"
                ));
            }
        }

        pub(crate) mod metrics {
            pub(crate) mod v1 {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.metrics.v1.rs"
                ));
            }
        }

        pub(crate) mod resource {
            pub(crate) mod v1 {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/opentelemetry.proto.resource.v1.rs"
                ));
            }
        }
    }
}
